# This is a basic workflow to help you get started with Actions
# Dummy line for triggering a repo change.

name: gooner_runnn

on: [workflow_dispatch, pull_request]

# Controls when the action will run. 
# on:
#  # Triggers the workflow on push or pull request events but only for the main branch
#  push:
#    branches: [ main ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!; echo $GITHUB_WORKSPACE

      - name: setting what.txt
        run: |
          python test_script.py $SUPER_SECRET $TJOBBA
        env:
          SUPER_SECRET: ${{ secrets.GUNNAR }}
          TJOBBA: tjubbu
     
      - name: push
        run: |
          git config user.email "gooner132@hotmail.com"; git config user.name "Gunnar Persson"; git add what.txt; git commit -m 'Automaticccc goonerAutomatic'; git push origin main
#          # git config --global user.email "gooner132@hotmail.com"; git config --global user.name "Gunnar Persson"; git add what.txt; git commit -m 'Automaticccc goonerAutomatic'; git push origin main

#      - name: pushORG
#        uses: github-actions-x/commit@v2.1
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          commit-message: 'Automatic gooner Automatic'
#          rebase: 'true'
          
      - name: reading what.txt
        run: |
          python test_script2.py
          
          
   
